### ISSUE TITLE
pthread.h

### ISSUE THREAD

**Issue by jonathanlinat** [Solokiller/halflife-updated-cmake#2]
Configuring VS2019 project using CMake GUI, I have:

```
Looking for C++ include pthread.h
Looking for C++ include pthread.h - not found
```

I used the recommended configuration included in Windows wiki article.

![image](https://user-images.githubusercontent.com/14064112/74599094-62ea7500-505b-11ea-9c89-87aa19d986f5.png)

**Comment by Solokiller** [comment]
That's not a problem. CMake checks for the presence of a lot of stuff during the initial setup and logs what it does and does not find. Unless it actually says something is an error you can just ignore it.
